server:
  port: 3301

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 5
      bootstrap-servers: ${spring.kafka.bootstrap-servers}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  mail:
    host: smtp.gmail.com
    port: 587
    username: "ENDEREÇO_EMAIL"
    password: "SENHA_EMAIL"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
