server:
  port: 3300

spring:
  application:
    name: vendas
  datasource:
    username: postgres
    password: 123456789
    url: "jdbc:postgresql://172.18.0.1:5432/venda?serverTimezone=UTC&useSSL=false"
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 5
      bootstrap-servers: ${spring.kafka.bootstrap-servers}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
